version: "3"
services:

    auth-db:
        image: postgres
        container_name: auth-db
        restart: always
        environment:
          - POSTGRES_DB=auth-db
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=terra
        ports: 
          - 5442:5432

    product-db:
        image: postgres
        container_name: product-db
        restart: always
        environment:
          - POSTGRES_DB=auth-db
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=terra
        ports: 
          - 5452:5432

    sales-db:
        image: mongo:4.4.6
        container_name: sales-db
        restart: always
        environment:
          - MONGO_INITDB_ROOT_USERNAME=admin
          - MONGO_INITDB_ROOT_PASSWORD=terra
        ports: 
          - 27017:27017
          - 28017:28017

    sales-rabbitmq:
        image: rabbitmq:3.12-management
        container_name: sales-rabbitmq
        ports:
          - 5672:5672
          - 25676:25676
          - 15672:15672
